const KEY='cet4-coach-v1';
// 已公布的笔试日期；未来场次暂用 6 / 12 月第二个周六作为备考预计日期。
// 2026 年下半年官方安排：https://cet.neea.cn/xhtml1/report/2609/1-1.htm
const EXAM_DATES = {'2026-06':'2026-06-13','2026-12':'2026-12-12'};
const EXAM_DAY_MS = 86400000, EXAM_CHINA_OFFSET = 8 * 3600000;
function getExamInfo(now = new Date()) {
  const time = Number(now), china = new Date(time + EXAM_CHINA_OFFSET);
  for (let year = china.getUTCFullYear(); year <= china.getUTCFullYear() + 1; year++) {
    for (const month of [6, 12]) {
      const session = year + '-' + String(month).padStart(2, '0');
      const confirmed = Object.prototype.hasOwnProperty.call(EXAM_DATES, session);
      const firstWeekday = new Date(Date.UTC(year, month - 1, 1)).getUTCDay();
      const estimatedDay = 8 + (6 - firstWeekday + 7) % 7;
      const date = EXAM_DATES[session] || session + '-' + String(estimatedDay).padStart(2, '0');
      const start = Date.parse(date + 'T09:00:00+08:00');
      const end = Date.parse(date + 'T11:20:00+08:00');
      if (time >= end) continue;
      const days = Math.max(0, Math.floor((start + EXAM_CHINA_OFFSET) / EXAM_DAY_MS) - Math.floor((time + EXAM_CHINA_OFFSET) / EXAM_DAY_MS));
      const status = time >= start ? 'ongoing' : days === 0 ? 'today' : 'upcoming';
      const dateText = year + ' 年 ' + month + ' 月 ' + Number(date.slice(-2)) + ' 日';
      return {date, dateText, start, end, confirmed, days, status, key: date + ':' + days + ':' + status};
    }
  }
}
function examCountdown(exam) {
  if (exam.status === 'ongoing') return (exam.confirmed ? '考试进行中' : '预计考试时段') + ' · 11:20 结束';
  if (exam.status === 'today') return (exam.confirmed ? '今天考试' : '预计今天考试') + ' · 09:00–11:20';
  return (exam.confirmed ? '距离考试' : '距离预计考试') + ' <strong>' + exam.days + '</strong> 天';
}
function examNotice(exam) {
  return exam.confirmed ? '按北京时间计算，考试结束后自动切换到下一场。' : '预计日期用于备考规划，正式日期以教育考试院公告为准。按北京时间计算。';
}
let renderedExamKey = '', examRefreshTimer;
function refreshExamClock() {
  clearTimeout(examRefreshTimer);
  const now = Date.now(), exam = getExamInfo(new Date(now));
  if ((view === 'home' || view === 'plan') && exam.key !== renderedExamKey) render();
  const midnight = (Math.floor((now + EXAM_CHINA_OFFSET) / EXAM_DAY_MS) + 1) * EXAM_DAY_MS - EXAM_CHINA_OFFSET;
  const nextBoundary = Math.min(midnight, ...[exam.start, exam.end].filter(time => time > now));
  examRefreshTimer = setTimeout(refreshExamClock, Math.max(50, Math.min(60000, nextBoundary - now + 25)));
}
const today=()=>new Date().toLocaleDateString('sv-SE');
const addDays=(n)=>{const d=new Date();d.setDate(d.getDate()+n);return d.toLocaleDateString('sv-SE')};
let state;
try{state=JSON.parse(localStorage.getItem(KEY))||{}}catch{state={}}
state.words??={};state.wrong??={};state.stats??={attempts:0,correct:0};state.daily??={};state.writing??={};
let view='home',current=null,queue=[],queueIndex=0,revealed=false,answered=false;
const $=s=>document.querySelector(s);
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}};
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const progress=()=>{const date=today();state.daily[date]??={words:0,questions:0,reading:0,listening:0,writing:0};return state.daily[date]};
const dueWords=()=>VOCAB.filter(v=>state.words[v[0]]?.due<=today());
const newWords=()=>VOCAB.filter(v=>!state.words[v[0]]);
function speak(s,rate=.82){if(!('speechSynthesis'in window)){alert('当前浏览器不支持语音朗读，请使用 Chrome 或 Edge。');return}speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(s);u.lang='en-US';u.rate=rate;u.pitch=1;speechSynthesis.speak(u)}
function nav(name){view=name;current=null;queue=[];queueIndex=0;answered=false;revealed=false;document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));render();window.scrollTo({top:0,behavior:'smooth'})}
function daysLeft(){return getExamInfo().days}
function streak(){let n=0,d=new Date();for(;;){let k=d.toLocaleDateString('sv-SE');if(!state.daily[k]||Object.values(state.daily[k]).reduce((a,b)=>a+b,0)===0)break;n++;d.setDate(d.getDate()-1)}return n}
function render(){let root=$('#main');root.innerHTML=({home:home,vocab:vocab,practice:practice,reading:reading,listening:listening,writing:writing,papers:papers,mock:mock,plan:plan}[view])();renderedExamKey=getExamInfo().key;bindCommon()}
function bindCommon(){document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.go)))}
function home(){let exam=getExamInfo(),p=progress(),due=dueWords().length,learned=Object.keys(state.words).length,correct=state.stats.attempts?Math.round(state.stats.correct/state.stats.attempts*100):0;return `<section class="hero"><div class="eyebrow">${exam.dateText} · 四级笔试${exam.confirmed?'':'（预计）'}</div><h1>从看懂一个词开始，<br><em>一步步走到考场。</em></h1><p>每天先学词，再读句子、做小题。不会也没关系，答错的题会回来。</p><div class="hero-actions"><button class="primary" data-go="vocab">开始今天的学习 →</button><span data-exam-countdown aria-live="polite">${examCountdown(exam)}</span></div><p class="exam-note">${examNotice(exam)}</p></section><section class="metrics"><div><strong>${learned}<small> / ${VOCAB.length}</small></strong><span>已学单词</span></div><div><strong>${due}</strong><span>今天待复习</span></div><div><strong>${correct}%</strong><span>练习正确率</span></div><div><strong>${streak()}</strong><span>连续学习天数</span></div></section><div class="section-title"><div><span class="eyebrow">TODAY'S PATH</span><h2>今天做这些就够了</h2></div><span class="muted">建议 25–35 分钟</span></div><section class="task-grid">${task('01','单词入门',p.words,12,'学 12 个词，复习到期词','vocab')}${task('02','小题练习',p.questions,8,'词义和句子填空','practice')}${task('03','读一小段',p.reading,1,'先看问题，再找答案','reading')}${task('04','听一句话',p.listening,1,'听关键词，不必听懂每个词','listening')}</section><section class="notice"><strong>从零基础开始的规则</strong><p>看不懂句子时，先找你认识的词和数字；点击「中文提示」再读一遍。每天重复，比一次做很多更有用。每周留一天做整套试卷，按真实时间练习。</p></section>`}
function task(num,name,done,target,description,to){return `<button class="task" data-go="${to}"><span class="task-num">${num}</span><strong>${escapeHtml(name)}</strong><span>${escapeHtml(description)}</span><div class="bar"><i style="width:${Math.min(100,done/target*100)}%"></i></div><small>${done} / ${target} 今日完成</small></button>`}
function vocab(){let pool=[...dueWords(),...newWords()].slice(0,12);if(!pool.length)pool=VOCAB.slice().sort((a,b)=>(state.words[a[0]]?.due||'').localeCompare(state.words[b[0]]?.due||''));if(!current||current.kind!=='word')current={kind:'word',item:pool[0],pool,index:0};let w=current.item,p=state.words[w[0]];return `<section class="page-head"><span class="eyebrow">STEP 01 · 单词</span><h1>先认得，再记住</h1><p>先猜意思，翻开后读例句。忘记是正常的，点「还不熟」明天再见。</p></section><div class="study-layout"><article class="flashcard"><div class="card-top"><span>第 ${current.index+1} / ${current.pool.length} 个</span><span>${p?'复习':'新词'}</span></div><div class="word">${escapeHtml(w[0])}</div><button class="sound" id="speakWord" aria-label="朗读单词">🔊 听发音</button>${revealed?`<div class="answer-panel"><div class="meaning">${escapeHtml(w[1])}</div><p>${escapeHtml(w[2])}</p><small>${escapeHtml(w[3])}</small><button class="text-button" id="speakSentence">🔊 听例句</button></div><div class="button-row"><button class="soft" id="forgot">还不熟 · 明天再见</button><button class="primary" id="known">记住了 · 继续</button></div>`:`<button class="primary reveal" id="reveal">显示中文与例句</button>`}</article><aside class="coach"><strong>学习方法</strong><ol><li>先看英文，试着猜。</li><li>听一遍发音，再看中文。</li><li>遮住中文，试着说出意思。</li><li>明天复习今天不熟的词。</li></ol><p>已学 <b>${Object.keys(state.words).length}</b> 词 · 待复习 <b>${dueWords().length}</b> 词</p></aside></div>`}
function nextWord(ok){let w=current.item[0],old=state.words[w]||{interval:0,seen:0,correct:0};let interval=ok?(old.interval===0?1:old.interval===1?3:Math.min(30,old.interval*2)):1;state.words[w]={interval,seen:old.seen+1,correct:old.correct+(ok?1:0),due:addDays(interval)};progress().words++;save();current.index++;if(current.index>=current.pool.length){current=null;revealed=false;nav('home');return}current.item=current.pool[current.index];revealed=false;render()}
function makeQuestions(kind){let out=[];if(kind==='all'||kind==='words'){for(let [i,w] of VOCAB.entries()){let options=shuffle([w[1],...shuffle(VOCAB.filter(x=>x[0]!==w[0]&&x[1]!==w[1])).slice(0,3).map(x=>x[1])]);out.push({id:'v'+i,kind:'词义',q:`${w[0]} 是什么意思？`,options,correct:options.indexOf(w[1]),tip:`${w[0]} = ${w[1]}。${w[2]} ${w[3]}`})}}if(kind==='all'||kind==='cloze'){CLOZE.forEach((x,i)=>{let opts=shuffle(x.o);out.push({id:'c'+i,kind:'句子',q:x.s,options:opts,correct:opts.indexOf(x.o[x.a]),tip:x.tip})})}return out}
function startQueue(kind){let all=makeQuestions(kind);let wrong=all.filter(x=>state.wrong[x.id]);let rest=all.filter(x=>!state.wrong[x.id]);queue=[...shuffle(wrong),...shuffle(rest)].slice(0,10);queueIndex=0;answered=false;renderQuestion()}
function practice(){return `<section class="page-head"><span class="eyebrow">STEP 02 · 小题练习</span><h1>一题一讲，慢慢来</h1><p>每组 10 题；错题优先出现。选错后先读中文解释，再做下一题。</p></section><section class="choice-grid"><button class="mode" id="startWords"><span>01</span><strong>认单词</strong><small>${VOCAB.length} 个原创词义题</small></button><button class="mode" id="startCloze"><span>02</span><strong>补句子</strong><small>${CLOZE.length} 个原创填空题</small></button><button class="mode" id="startMixed"><span>03</span><strong>混合练习</strong><small>词义、句子随机混合</small></button></section><div id="questionBox"></div>`}
function renderQuestion(){let box=$('#questionBox');if(!box||!queue.length)return;let q=queue[queueIndex];box.innerHTML=`<article class="question-card"><div class="question-meta"><span>${escapeHtml(q.kind)}</span><span>${queueIndex+1} / ${queue.length}</span></div><h2>${escapeHtml(q.q)}</h2><div class="options">${q.options.map((o,i)=>`<button data-answer="${i}" class="option">${'ABCD'[i]}. ${escapeHtml(o)}</button>`).join('')}</div><div id="feedback" aria-live="polite"></div></article>`;box.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>answer(q,Number(b.dataset.answer),'questions')))}
function answer(q,choice,type){if(answered)return;answered=true;let ok=choice===q.correct;state.stats.attempts++;if(ok){state.stats.correct++;delete state.wrong[q.id]}else state.wrong[q.id]=true;progress()[type]++;save();document.querySelectorAll(type==='listening'?'[data-listen-answer]':'[data-answer]').forEach((b,i)=>{b.disabled=true;if(i===q.correct)b.classList.add('correct');else if(i===choice)b.classList.add('incorrect')});$('#feedback').innerHTML=`<div class="feedback ${ok?'good':'bad'}"><strong>${ok?'答对了！':'再记一下：正确答案是 '+escapeHtml(q.options[q.correct])}</strong><p>${escapeHtml(q.tip)}</p><button class="primary" id="nextQ">${queueIndex+1<queue.length?'下一题 →':'完成本组'}</button></div>`;$('#nextQ').onclick=()=>{queueIndex++;answered=false;if(queueIndex<queue.length)renderQuestion();else{queue=[];$('#questionBox').innerHTML='<div class="finish">这组完成了！错题已加入复习。<button class="primary" id="again">再来一组</button></div>';$('#again').onclick=()=>startQueue('all')}}}
function reading(){if(!current||current.kind!=='reading')current={kind:'reading',index:0};let x=READINGS[current.index],key='r'+current.index;let qs=x.qs.map((q,i)=>{let id=key+'-'+i;return `<div class="read-q"><strong>${i+1}. ${escapeHtml(q.q)}</strong><div class="options">${q.o.map((o,j)=>`<button class="option" data-read="${i}" data-choice="${j}" ${state.wrong[id]==='done'?'disabled':''}>${'ABCD'[j]}. ${escapeHtml(o)}</button>`).join('')}</div><div class="read-feedback" id="rf${i}"></div></div>`}).join('');return `<section class="page-head"><span class="eyebrow">STEP 03 · 阅读</span><h1>先看问题，再读短文</h1><p>这些是原创入门短文，帮助你练定位；周末再练真实试卷的长篇阅读。</p></section><div class="switcher">${READINGS.map((r,i)=>`<button class="chip ${i===current.index?'selected':''}" data-reading="${i}">${i+1}. ${escapeHtml(r.title)}</button>`).join('')}</div><div class="study-layout"><article class="passage"><span class="eyebrow">SHORT READING</span><h2>${escapeHtml(x.title)}</h2><p class="english">${escapeHtml(x.text)}</p><button class="soft" id="showChinese">${revealed?'隐藏中文提示':'显示中文提示'}</button>${revealed?`<div class="translation"><p>${escapeHtml(x.cn)}</p><small>${escapeHtml(x.gloss)}</small></div>`:''}</article><aside class="coach"><strong>三步找答案</strong><ol><li>先读题目，圈出人名、时间、数字。</li><li>在短文中找相同或近义信息。</li><li>只根据短文选，不凭自己的常识猜。</li></ol></aside></div><article class="question-card read-list">${qs}</article>`}
function listening(){if(!current||current.kind!=='listening')current={kind:'listening',index:0};let x=LISTENINGS[current.index];return `<section class="page-head"><span class="eyebrow">STEP 04 · 听力</span><h1>先抓一个关键词</h1><p>原创短句用系统英语语音朗读。建议先听两遍，再看选项。</p></section><div class="switcher">${LISTENINGS.map((_,i)=>`<button class="chip ${i===current.index?'selected':''}" data-listening="${i}">第 ${i+1} 句</button>`).join('')}</div><article class="question-card listen-card"><div class="listening-icon">◖)))</div><button class="primary" id="playListening">播放英语（可重复）</button><button class="soft" id="showScript">${revealed?'隐藏原文':'看英文原文与中文'}</button>${revealed?`<div class="translation"><p>${escapeHtml(x.script)}</p><small>${escapeHtml(x.cn)}</small></div>`:''}<h2>${escapeHtml(x.q)}</h2><div class="options">${x.o.map((o,i)=>`<button class="option" data-listen-answer="${i}">${'ABCD'[i]}. ${escapeHtml(o)}</button>`).join('')}</div><div id="feedback"></div></article>`}
function writing(){if(!current||current.kind!=='writing')current={kind:'writing',index:0};let x=WRITING[current.index];return `<section class="page-head"><span class="eyebrow">STEP 05 · 写作与翻译</span><h1>先写短句，再写完整段落</h1><p>先自己写，再看参考。写作可以检查常见错误并获得离线练习估分；它不是官方或人工阅卷分数。</p></section><div class="switcher">${WRITING.map((v,i)=>`<button class="chip ${i===current.index?'selected':''}" data-writing="${i}">${v.type} ${i+1}</button>`).join('')}</div><article class="question-card write-card"><span class="tag">${x.type}</span><h2>${escapeHtml(x.prompt)}</h2><p class="gloss">关键词：${escapeHtml(x.words)}</p><details><summary>不会写？点开句子框架</summary><p>${escapeHtml(x.frame)}</p></details><textarea id="myWriting" lang="en" spellcheck="true" placeholder="先写在这里。写错没关系，从一句简单的英文开始。">${escapeHtml(state.writing[current.index]||'')}</textarea><div class="button-row"><button class="soft" id="saveWriting">保存我的答案</button>${x.type==='写作'?'<button class="primary" id="gradeWriting">检查错误并估分</button>':''}<button class="soft" id="showModel">${revealed?'隐藏参考写法':'看参考写法'}</button></div><div id="gradeResult" aria-live="polite"></div>${revealed?`<div class="translation"><strong>一种参考写法</strong><p>${escapeHtml(x.model)}</p><small>用自己的简单句表达清楚即可；范文并非唯一答案。</small></div>`:''}</article>`}
function audioLinks(){let h='<div class="paper-year"><h2>真题听力音频 · 8 份</h2><p class="muted">每次考试第 1 套；点击后浏览器播放或下载。先完成入门短句，再尝试正式语速。</p><div class="paper-grid">';for(let year=2025;year>=2022;year--)for(let month of ['12','06']){let file=`cet4-${year}-${month}-set-01.mp3`;h+=`<a class="paper" href="历年试卷/听力音频/${file}" target="_blank" rel="noopener"><span>MP3</span><strong>${year} 年 ${Number(month)} 月 · 第 1 套</strong><small>打开本地音频 ↗</small></a>`}return h+'</div></div>'}
function papers(){let html='<div class="paper-year"><h2>2026 年 6 月 · 最新真题整理版</h2><div class="paper-grid">';for(let n=1;n<=3;n++){let file=`cet4-2026-06-set-${String(n).padStart(2,'0')}.pdf`,answer=`cet4-2026-06-set-${String(n).padStart(2,'0')}-answers.pdf`;html+=`<a class="paper" href="历年试卷/2026年6月/${file}" target="_blank" rel="noopener"><span>PDF · 原卷</span><strong>2026 年 6 月 · 第 ${n} 套</strong><small>${n===3?'听力与第 1 套共用':'先做这一份，再看解析'}</small></a><a class="paper" href="历年试卷/2026年6月/${answer}" target="_blank" rel="noopener"><span>PDF · 参考解析</span><strong>第 ${n} 套 · 答案与解析</strong><small>第三方参考答案，并非官方标准答案</small></a>`}html+='</div><p class="muted">本次第 1、2 套听力可在 <a href="https://english-exam.lazynote.cn/cet4/paper/2026-06-1/" target="_blank" rel="noopener">第 1 套资料页</a>、<a href="https://english-exam.lazynote.cn/cet4/paper/2026-06-2/" target="_blank" rel="noopener">第 2 套资料页</a>在线播放；需要联网。</p></div>';for(let year=2025;year>=2022;year--){html+=`<div class="paper-year"><h2>${year} 年</h2><div class="paper-grid">`;for(let month of ['12','06'])for(let n=1;n<=3;n++){let file=`cet4-${year}-${month}-set-${String(n).padStart(2,'0')}.pdf`;html+=`<a class="paper" href="历年试卷/${file}" target="_blank" rel="noopener"><span>PDF</span><strong>${year} 年 ${Number(month)} 月 · 第 ${n} 套</strong><small>${year===2022&&month==='06'&&n===3?'仅写作与翻译；客观题见第 2 套':'打开本地试卷 ↗'}</small></a>`}html+='</div></div>'}return `<section class="page-head"><span class="eyebrow">2022—2026 · 27 套</span><h1>历年试卷资料室</h1><p>新加入 2026 年 6 月三套整理版及参考解析。先学会短句与定位，再逐步接近完整试卷。</p></section><div class="notice"><strong>资料说明</strong><p>2026 年 6 月三套来自懒笔记整理站；2022—2025 年 24 套来自另一第三方整理站，均非教育考试院官方发布的真题包。2026 年 6 月第 3 套听力与第 1 套共用；2022 年 6 月第 3 套仅单列写作、翻译，客观题与第 2 套共用。解析版答案仅供练习参考。2022—2025 年另附 8 份第 1 套听力音频。</p></div>${html}${audioLinks()}`}
function plan(){let exam=getExamInfo(),left=exam.days,phase=left>56?1:left>28?2:3;return `<section class="page-head"><span class="eyebrow">NEXT CET-4 EXAM</span><h1>从今天到考试的路线</h1><p>${exam.dateText}${exam.confirmed?'':'（预计）'} · 四级笔试。<span data-exam-countdown aria-live="polite">${examCountdown(exam)}</span>。以每天约 30 分钟为基础，周末加一套卷。</p><p class="muted">${examNotice(exam)}</p></section><section class="timeline"><div class="phase ${phase===1?'now':''}"><span>阶段 1 · 基础</span><h2>现在起，先认词读句</h2><p>每天 12 个词，复习到期词；做 8 道小题，读 1 篇短文，听 1 句。先形成稳定习惯。</p></div><div class="phase ${phase===2?'now':''}"><span>阶段 2 · 题型</span><h2>把短练习接到真题</h2><p>每周做 2 次阅读和听力专项。用本地 PDF 找题目；先做后查。记录错因：不认识词、没定位、时间不够。</p></div><div class="phase ${phase===3?'now':''}"><span>阶段 3 · 模考</span><h2>按真实时间练整卷</h2><p>每周至少 1 次完整模考，125 分钟。写作 30 分钟、听力 25 分钟、阅读 40 分钟、翻译 30 分钟。最后一周复习错题与常用句。</p></div></section><section class="notice"><strong>分值如何安排精力</strong><p>官方笔试结构：听力 35%，阅读 35%，写作 15%，翻译 15%。因此每天都要碰一点听力和阅读；写作与翻译每周练 2–3 次。目标分数请按自己学校的要求确认，练习正确率不能直接换算四级分数。</p></section><button class="primary" data-go="vocab">从今天的单词开始 →</button>`}
document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));
document.addEventListener('click',e=>{let id=e.target.id;if(id==='reveal'){revealed=true;render()}if(id==='speakWord')speak(current.item[0],.75);if(id==='speakSentence')speak(current.item[2]);if(id==='forgot')nextWord(false);if(id==='known')nextWord(true);if(id==='startWords')startQueue('words');if(id==='startCloze')startQueue('cloze');if(id==='startMixed')startQueue('all');if(e.target.dataset.reading!==undefined){current={kind:'reading',index:Number(e.target.dataset.reading)};revealed=false;render()}if(id==='showChinese'){revealed=!revealed;render()}if(e.target.dataset.read!==undefined){let i=Number(e.target.dataset.read),j=Number(e.target.dataset.choice),x=READINGS[current.index].qs[i],key=`r${current.index}-${i}`,wrap=e.target.closest('.read-q');if(wrap.dataset.done)return;wrap.dataset.done='1';let ok=j===x.a;state.stats.attempts++;if(ok){state.stats.correct++;delete state.wrong[key]}else state.wrong[key]=true;progress().reading++;save();wrap.querySelectorAll('.option').forEach((b,k)=>{b.disabled=true;if(k===x.a)b.classList.add('correct');else if(k===j)b.classList.add('incorrect')});wrap.querySelector('.read-feedback').innerHTML=`<div class="feedback ${ok?'good':'bad'}">${ok?'答对了！':'正确答案：'+escapeHtml(x.o[x.a])} ${escapeHtml(x.tip)}</div>`}if(e.target.dataset.listening!==undefined){current={kind:'listening',index:Number(e.target.dataset.listening)};answered=false;revealed=false;render()}if(id==='playListening')speak(LISTENINGS[current.index].script,.76);if(id==='showScript'){revealed=!revealed;render()}if(e.target.dataset.listenAnswer!==undefined){let x=LISTENINGS[current.index],i=Number(e.target.dataset.listenAnswer);answer({id:'l'+current.index,options:x.o,correct:x.a,tip:`${x.tip} 原文：${x.script} 中文：${x.cn}`},i,'listening');let b=$('#nextQ');if(b)b.onclick=()=>{current.index=(current.index+1)%LISTENINGS.length;answered=false;revealed=false;render()}}if(e.target.dataset.writing!==undefined){current={kind:'writing',index:Number(e.target.dataset.writing)};revealed=false;render()}if(id==='saveWriting'){state.writing[current.index]=$('#myWriting').value;progress().writing++;save();e.target.textContent='已保存 ✓'}if(id==='showModel'){state.writing[current.index]=$('#myWriting').value;save();revealed=!revealed;render()}});
render();
refreshExamClock();
window.addEventListener('focus',refreshExamClock);
window.addEventListener('pageshow',refreshExamClock);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshExamClock()});


