// 教学内容为原创。词表依据 2022—2025 试卷主题与常见基础词整理，非官方词频排名。
const VOCAB = [
['improve','改善；提高','We can improve our study habits.','我们可以改善学习习惯。'],
['suggest','建议','I suggest a short walk after class.','我建议课后散步一会儿。'],
['provide','提供','The library provides free books.','图书馆提供免费图书。'],
['support','支持；帮助','Friends support each other.','朋友互相支持。'],
['develop','发展；培养','Reading helps us develop ideas.','阅读帮助我们培养想法。'],
['reduce','减少','We should reduce food waste.','我们应该减少食物浪费。'],
['increase','增加','Exercise can increase energy.','运动可以增加精力。'],
['include','包括','The plan includes three steps.','这个计划包括三个步骤。'],
['require','需要；要求','The course requires daily practice.','这门课要求每天练习。'],
['allow','允许','The school allows students to borrow bikes.','学校允许学生借自行车。'],
['offer','提供','The club offers free lessons.','社团提供免费课程。'],
['create','创造；建立','Small changes can create big results.','小改变能带来大结果。'],
['consider','考虑','Please consider my idea.','请考虑我的想法。'],
['decide','决定','She decided to join the club.','她决定加入社团。'],
['choose','选择','Choose the answer with care.','认真选择答案。'],
['compare','比较','Compare the two opinions.','比较这两种观点。'],
['explain','解释','The teacher explains the rule.','老师解释这条规则。'],
['describe','描述','Please describe the picture.','请描述这张图片。'],
['mention','提到','The writer mentions a new problem.','作者提到一个新问题。'],
['find','发现；找到','Find the key word in the question.','在问题中找到关键词。'],
['result','结果','The result surprised everyone.','这个结果让大家惊讶。'],
['reason','原因；理由','What is the reason for the change?','变化的原因是什么？'],
['effect','影响；效果','Sleep has an effect on memory.','睡眠对记忆有影响。'],
['cause','导致；原因','Stress can cause health problems.','压力可能导致健康问题。'],
['problem','问题','We need to solve this problem.','我们需要解决这个问题。'],
['solution','解决办法','This is a simple solution.','这是一个简单的解决办法。'],
['change','改变','A small change can help.','一个小改变就有帮助。'],
['choice','选择','It is a difficult choice.','这是一个艰难的选择。'],
['chance','机会；可能性','This is a chance to learn.','这是一个学习的机会。'],
['challenge','挑战','English is a challenge for me.','英语对我来说是个挑战。'],
['important','重要的','Sleep is important for students.','睡眠对学生很重要。'],
['necessary','必要的','Practice is necessary.','练习是必要的。'],
['possible','可能的','Is another answer possible?','还有别的答案可能正确吗？'],
['likely','可能的','It is likely to rain.','可能会下雨。'],
['common','常见的；共同的','This is a common mistake.','这是一个常见错误。'],
['different','不同的','People have different ideas.','人们有不同的想法。'],
['similar','相似的','The two words have similar meanings.','这两个词意思相近。'],
['available','可获得的；有空的','Free books are available online.','网上有免费的书。'],
['public','公众的；公共的','The park is open to the public.','公园向公众开放。'],
['private','私人的','Keep your password private.','不要泄露你的密码。'],
['community','社区','Students help their community.','学生帮助社区。'],
['society','社会','Education benefits society.','教育有益于社会。'],
['culture','文化','Food is part of culture.','食物是文化的一部分。'],
['traditional','传统的','This is a traditional festival.','这是一个传统节日。'],
['local','当地的','We visited a local museum.','我们参观了当地的博物馆。'],
['environment','环境','We should protect the environment.','我们应该保护环境。'],
['resource','资源','Water is an important resource.','水是一种重要资源。'],
['energy','能源；精力','Walking gives me more energy.','散步让我更有精力。'],
['waste','浪费；废物','Do not waste clean water.','不要浪费干净的水。'],
['protect','保护','Trees help protect the soil.','树木帮助保护土壤。'],
['health','健康','Exercise is good for health.','运动有益健康。'],
['healthy','健康的','A healthy meal can be simple.','健康的一餐可以很简单。'],
['exercise','锻炼','I exercise three times a week.','我每周锻炼三次。'],
['habit','习惯','Reading daily is a good habit.','每天阅读是个好习惯。'],
['stress','压力','Music helps me reduce stress.','音乐帮助我减轻压力。'],
['sleep','睡眠；睡觉','Good sleep helps us learn.','良好的睡眠帮助我们学习。'],
['diet','饮食','A balanced diet matters.','均衡饮食很重要。'],
['balance','平衡','Students need a balance between study and rest.','学生需要平衡学习和休息。'],
['skill','技能','Listening is an important skill.','听力是一项重要技能。'],
['knowledge','知识','Books give us knowledge.','书籍给我们知识。'],
['experience','经验；经历','The job gave her experience.','这份工作给了她经验。'],
['opportunity','机会','Volunteering is a learning opportunity.','志愿服务是学习机会。'],
['education','教育','Education can change lives.','教育能够改变人生。'],
['research','研究','Research shows that sleep helps memory.','研究表明睡眠有助于记忆。'],
['study','学习；研究','I study English every day.','我每天学习英语。'],
['learn','学习','We learn from mistakes.','我们从错误中学习。'],
['practice','练习','Daily practice is useful.','每天练习很有用。'],
['review','复习','Review new words tomorrow.','明天复习新单词。'],
['remember','记住','I remember this word now.','我现在记住这个词了。'],
['understand','理解','I understand the main idea.','我理解中心意思。'],
['focus','专注；重点','Focus on the question first.','先关注问题。'],
['attention','注意','Pay attention to the date.','注意日期。'],
['information','信息','The notice gives useful information.','通知提供了有用信息。'],
['detail','细节','The answer is in the last detail.','答案在最后一个细节中。'],
['opinion','观点；意见','What is your opinion?','你的意见是什么？'],
['idea','想法','She has a good idea.','她有个好想法。'],
['example','例子','Give one clear example.','举一个清楚的例子。'],
['evidence','证据','The article gives evidence.','文章给出了证据。'],
['main','主要的','Find the main idea of the paragraph.','找出段落的中心意思。'],
['purpose','目的','What is the purpose of the notice?','这则通知的目的是什么？'],
['benefit','好处；受益','Students benefit from reading.','学生从阅读中受益。'],
['advantage','优点','One advantage is low cost.','一个优点是成本低。'],
['disadvantage','缺点','A disadvantage is the long wait.','一个缺点是等待时间长。'],
['method','方法','This method is easy to use.','这个方法容易使用。'],
['process','过程','Learning is a long process.','学习是一个长期过程。'],
['activity','活动','The school has many activities.','学校有许多活动。'],
['volunteer','志愿者；自愿做','I volunteer at the library.','我在图书馆做志愿者。'],
['service','服务','The clinic provides a useful service.','诊所提供有用的服务。'],
['campus','校园','Our campus has a new library.','我们校园有一座新图书馆。'],
['library','图书馆','I study in the library.','我在图书馆学习。'],
['course','课程','This course is for beginners.','这门课面向初学者。'],
['online','在线的','The course is available online.','这门课可以在线学习。'],
['technology','技术','Technology can support learning.','技术可以辅助学习。'],
['digital','数字的','Digital books are easy to carry.','电子书便于携带。'],
['communicate','交流','We communicate by email.','我们通过邮件交流。'],
['relationship','关系','Trust helps a relationship.','信任有助于维系关系。'],
['participate','参加','Many students participate in the event.','许多学生参加活动。'],
['organize','组织','The club will organize a meeting.','社团将组织一次会议。'],
['responsibility','责任','We have a responsibility to help.','我们有责任提供帮助。'],
['future','未来','Think about your future.','想想你的未来。'],
['goal','目标','My goal is to pass CET-4.','我的目标是通过英语四级。'],
['achieve','实现','Small steps help us achieve a goal.','小步骤帮助我们实现目标。'],
['success','成功','Practice brings success.','练习带来成功。'],
['however','然而','The idea is good; however, it costs too much.','这个想法不错；然而，它太贵了。'],
['therefore','因此','It rained; therefore, we stayed inside.','下雨了，因此我们待在室内。'],
['although','虽然','Although it was hard, she tried.','虽然很难，她还是试了。'],
['because','因为','I stayed home because I was tired.','因为累了，我待在家里。'],
['instead','代替；反而','Walk instead of taking a taxi.','步行代替打车。'],
['especially','尤其','I like reading, especially short stories.','我喜欢阅读，尤其是短篇故事。'],
['finally','最后','Finally, check your answers.','最后，检查答案。']
];

const CLOZE = [
{s:'The library will ___ free books to new students.',o:['provide','reduce','forget','refuse'],a:0,tip:'provide = 提供。句意：图书馆将向新生提供免费图书。'},
{s:'Good sleep can ___ your memory.',o:['improve','waste','borrow','close'],a:0,tip:'improve = 改善。句意：良好的睡眠能改善记忆力。'},
{s:'We should ___ food waste on campus.',o:['reduce','increase','describe','choose'],a:0,tip:'reduce = 减少。后面接 food waste（食物浪费）。'},
{s:'She exercises every day to stay ___.',o:['healthy','public','local','digital'],a:0,tip:'healthy = 健康的。stay + 形容词。'},
{s:'The teacher asked us to give one ___ for our opinion.',o:['reason','water','chair','hour'],a:0,tip:'reason = 理由。观点需要理由。'},
{s:'Many students ___ in volunteer activities.',o:['participate','protect','compare','remember'],a:0,tip:'participate in = 参加。'},
{s:'The article gives useful ___ about the exam.',o:['information','exercise','festival','energy'],a:0,tip:'information = 信息；不可数名词。'},
{s:'The school wants to ___ a greener campus.',o:['create','borrow','hear','miss'],a:0,tip:'create = 创造、建立。'},
{s:'Please ___ the two ideas before you decide.',o:['compare','sleep','translate','offer'],a:0,tip:'compare = 比较。'},
{s:'Online classes are ___ to students at home.',o:['available','private','impossible','silent'],a:0,tip:'available = 可获得的、可使用的。'},
{s:'Students need to find a ___ between study and rest.',o:['balance','challenge','mistake','notice'],a:0,tip:'balance = 平衡。'},
{s:'The main ___ of this notice is to tell us the exam date.',o:['purpose','method','culture','food'],a:0,tip:'purpose = 目的。'},
{s:'There is no easy ___ to every problem.',o:['solution','campus','passage','service'],a:0,tip:'solution to a problem = 问题的解决办法。'},
{s:'Technology can ___ students in their learning.',o:['support','waste','refuse','forget'],a:0,tip:'support = 支持、帮助。'},
{s:'We need more ___ to know if the idea works.',o:['evidence','exercise','weather','lunch'],a:0,tip:'evidence = 证据。'},
{s:'Reading every day is a useful ___.',o:['habit','choice','building','event'],a:0,tip:'habit = 习惯。'},
{s:'The plan has one clear ___: it saves time.',o:['advantage','disadvantage','problem','mistake'],a:0,tip:'advantage = 优点。'},
{s:'The report ___ a change in student life.',o:['mentions','reduces','eats','sleeps'],a:0,tip:'mention = 提到。'},
{s:'The lesson was difficult; ___, I learned a lot.',o:['however','because','before','instead'],a:0,tip:'however = 然而，表示转折。'},
{s:'It rained; ___, the outdoor event was canceled.',o:['therefore','although','especially','instead'],a:0,tip:'therefore = 因此，表示结果。'},
{s:'___ the task was hard, we finished it.',o:['Although','Because','Therefore','Finally'],a:0,tip:'although = 虽然，表示让步。'},
{s:'To understand the passage, first find its ___ idea.',o:['main','private','local','digital'],a:0,tip:'main idea = 中心思想。'},
{s:'A good learner will ___ new words after a day.',o:['review','waste','provide','refuse'],a:0,tip:'review = 复习。'},
{s:'The program gives beginners a chance to ___ English.',o:['practice','cause','include','reduce'],a:0,tip:'practice = 练习。'}
];

const READINGS = [
{title:'校园图书馆',text:'Our university library opens at 8 a.m. It now offers a quiet room for students who need to focus. Students can also borrow a digital book for two weeks. The library asks users to keep the room clean and return books on time.',cn:'学校图书馆早上八点开门。现在为需要专注学习的学生提供安静自习室。学生还可以借电子书两周。图书馆要求保持整洁并按时还书。',gloss:'offer 提供 · focus 专注 · borrow 借 · return 归还',qs:[{q:'What new place does the library offer?',o:['A quiet room','A sports field','A clinic','A restaurant'],a:0,tip:'定位第二句：offers a quiet room。'},{q:'How long can students borrow a digital book?',o:['Two weeks','One day','One month','One year'],a:0,tip:'定位第三句：for two weeks。'}]},
{title:'健康习惯',text:'Many students stay up late before exams. But research shows that sleep helps memory. Mei studies for an hour, takes a short break, and goes to bed before midnight. She says this simple habit helps her feel less stressed.',cn:'许多学生考前熬夜。但研究表明睡眠有助于记忆。梅学习一小时、稍作休息，并在午夜前睡觉。她说这个简单习惯让她压力更小。',gloss:'stay up late 熬夜 · research 研究 · memory 记忆 · stressed 有压力的',qs:[{q:'What does research show?',o:['Sleep helps memory','Late nights are useful','Breaks waste time','Exams are easy'],a:0,tip:'定位第二句：sleep helps memory。'},{q:'How does Mei feel with this habit?',o:['Less stressed','More worried','More tired','Less healthy'],a:0,tip:'定位末句：less stressed。'}]},
{title:'绿色校园',text:'A student group wants to reduce food waste. It puts small signs in the dining hall: “Take only what you can eat.” In one month, the amount of wasted food falls. The group plans to share its idea with other schools.',cn:'学生组织想减少食物浪费，于是在食堂放上“按需取餐”的标语。一个月后，浪费的食物减少了。小组计划把这个方法分享给其他学校。',gloss:'reduce 减少 · sign 标语 · amount 数量 · share 分享',qs:[{q:'What is the group trying to reduce?',o:['Food waste','Study time','Library books','School buses'],a:0,tip:'定位第一句：reduce food waste。'},{q:'What happened after one month?',o:['Less food was wasted','The dining hall closed','More signs were removed','Students stopped eating'],a:0,tip:'falls 表示下降。'}]},
{title:'社区服务',text:'Lin volunteers at a community center every Saturday. She teaches older people how to use a phone to make video calls. At first, she thought the work would be difficult. Now she enjoys it because she can help others and learn to communicate clearly.',cn:'林每周六在社区中心做志愿者。她教老年人用手机打视频电话。开始她认为这项工作会很难，现在她喜欢它，因为既能帮助别人，又能学会清楚地交流。',gloss:'volunteer 志愿服务 · older people 老年人 · at first 起初 · communicate 交流',qs:[{q:'What does Lin teach?',o:['How to make video calls','How to cook','How to exercise','How to write essays'],a:0,tip:'定位第二句：make video calls。'},{q:'Why does Lin enjoy the work now?',o:['She helps others and learns communication','She gets free phones','She works only once a year','She avoids studying'],a:0,tip:'定位末句 because 之后的原因。'}]},
{title:'恰当使用技术',text:'An online tool can help students check new words quickly. However, it cannot replace thinking. When Jia reads an English article, she first guesses a word from the sentence. Then she checks the tool. This method helps her remember the word.',cn:'在线工具可以帮助学生快速查词，但不能代替思考。佳读英语文章时，先根据句子猜词，再用工具核对。这种方法帮助她记住单词。',gloss:'however 然而 · replace 代替 · guess 猜测 · method 方法',qs:[{q:'What does Jia do first?',o:['Guess from the sentence','Check the tool','Close the article','Ask a friend'],a:0,tip:'先看 first 后面的动作。'},{q:'What is the main idea?',o:['Use tools after thinking','Never use online tools','Reading is not useful','Memorize every word first'],a:0,tip:'首尾句概括：先思考，再用工具。'}]},
{title:'校园活动通知',text:'The English club will hold a short film night on Friday at 7 p.m. in Room 204. The event is free, but students should sign up by Thursday. After the film, a teacher will lead a simple discussion in English. Beginners are welcome.',cn:'英语社团周五晚上七点在 204 教室举办短片之夜。活动免费，但应在周四前报名。观影后老师会带领简单的英语讨论，欢迎初学者。',gloss:'hold 举办 · sign up 报名 · discussion 讨论 · beginner 初学者',qs:[{q:'When should students sign up?',o:['By Thursday','On Saturday','After the film','Next month'],a:0,tip:'定位 should sign up by Thursday。'},{q:'Who can join?',o:['Beginners too','Only teachers','Only film makers','Only seniors'],a:0,tip:'末句 Beginners are welcome。'}]}
];

const LISTENINGS = [
{script:'The library will close at five today. It usually closes at eight.',q:'今天图书馆几点关门？',o:['五点','八点','六点','九点'],a:0,tip:'听到 today 对应 five；usually 对应平时的 eight。',cn:'图书馆今天五点关门。平时八点关门。'},
{script:'Anna missed the bus, so she walked to school. It took her twenty minutes.',q:'Anna 怎么去学校？',o:['步行','坐公交','骑车','坐地铁'],a:0,tip:'missed the bus 后面说 walked to school。',cn:'Anna 错过公交车，所以步行到学校，花了二十分钟。'},
{script:'The English club meeting is on Thursday, not Tuesday. It starts at six in Room 204.',q:'英语社团哪天开会？',o:['周四','周二','周一','周六'],a:0,tip:'not Tuesday 是干扰信息；正确是 Thursday。',cn:'英语社团周四开会，不是周二。六点在 204 教室开始。'},
{script:'The new course is free for students. Please sign up online before Friday.',q:'学生如何报名？',o:['网上报名','到办公室报名','电话报名','无需报名'],a:0,tip:'听 sign up online。',cn:'新课程对学生免费，请在周五之前网上报名。'},
{script:'The woman wants to buy a book, but the shop is closed. She will order it online instead.',q:'她最后会怎样买书？',o:['网上订购','去实体店','请朋友代买','不买了'],a:0,tip:'instead 表示改变计划；order it online。',cn:'女士想买书，但书店关门，所以改为网上订购。'},
{script:'The talk is about healthy habits. The speaker suggests more sleep and less screen time at night.',q:'演讲者建议什么？',o:['晚上少看屏幕，多睡觉','晚上多看屏幕','减少睡眠','停止运动'],a:0,tip:'more sleep and less screen time at night。',cn:'讲座谈健康习惯，演讲者建议多睡觉，晚上少看屏幕。'}
];

const WRITING = [
{type:'写作',prompt:'向学校建议如何改善图书馆服务。写出一个问题、两条建议。',words:'library 图书馆 · improve 改善 · suggest 建议 · provide 提供',frame:'I am writing to suggest ways to improve ___. First, ___. Second, ___. I believe these changes will help students.',model:'I am writing to suggest ways to improve our library. First, it could open one hour earlier during exam weeks. This would give students more quiet study time. Second, the library could provide a simple online system to show which seats are available. Students would then spend less time looking for a place to study. These changes are easy to understand and useful for many students. I hope the library will consider these suggestions.'},
{type:'写作',prompt:'谈谈大学生如何养成健康的生活习惯。',words:'healthy 健康的 · exercise 锻炼 · sleep 睡眠 · habit 习惯',frame:'A healthy life is important for students. First, ___. Also, ___. In my view, ___.',model:'A healthy life is important for college students. First, we should get enough sleep. Good sleep helps us remember what we learn. Also, we can do simple exercise, such as walking for twenty minutes each day. Healthy food matters too. We do not need to change everything at once. One small habit can lead to another. In my view, regular practice is more useful than a perfect plan that we cannot follow.'},
{type:'写作',prompt:'谈谈学生应怎样恰当地使用 AI 辅助学习。',words:'technology 技术 · support 辅助 · understand 理解 · instead 代替',frame:'AI can help students ___. However, we should ___. For example, ___.',model:'AI tools can support learning when we use them carefully. For example, a student can ask a tool to explain a difficult word or show another example. However, students should try to think first. If a tool writes every answer for us, we may not understand the lesson. We should check its answers and use it to practice. In this way, technology can save time and help us learn more.'},
{type:'翻译',prompt:'翻译：图书馆为学生提供安静的学习空间。',words:'library 图书馆 · provide 提供 · quiet 安静的 · space 空间',frame:'The library provides ...',model:'The library provides students with a quiet place to study.'},
{type:'翻译',prompt:'翻译：越来越多的大学生参加社区志愿服务。',words:'more and more 越来越多 · take part in 参加 · community service 社区服务',frame:'More and more college students ...',model:'More and more college students take part in community volunteer service.'},
{type:'翻译',prompt:'翻译：适当的运动可以减轻压力并改善健康。',words:'regular exercise 适当的运动 · reduce 减轻 · improve 改善',frame:'Regular exercise can ...',model:'Regular exercise can reduce stress and improve health.'}
];
