// 2026 年 6 月题目主题与基础表达扩展；所有教学例句和小题为原创。
VOCAB.push(...[
['proposal','提议；建议','The student wrote a proposal for the library.','这名学生为图书馆写了一份建议。'],
['necessity','必要性','We should discuss the necessity of this rule.','我们应该讨论这项规定的必要性。'],
['practical','实际可行的','The plan is simple and practical.','这个计划简单而且可行。'],
['practicality','可行性','Cost affects the practicality of the plan.','成本影响这个计划的可行性。'],
['project','项目','Our group started a research project.','我们小组开始了一个研究项目。'],
['robot','机器人','A robot can carry books in the library.','机器人可以在图书馆搬运书籍。'],
['application','应用；申请','This application helps students find rooms.','这个应用帮助学生找教室。'],
['automatic','自动的','The door has an automatic lock.','这扇门有自动锁。'],
['efficient','高效的','A clear plan makes work more efficient.','清晰的计划让工作更高效。'],
['convenient','方便的','Online booking is convenient for students.','网上预约对学生很方便。'],
['replace','代替','Technology should not replace human care.','技术不应代替人的关怀。'],
['repetitive','重复的','Robots can do repetitive tasks.','机器人可以做重复性工作。'],
['innovation','创新','Innovation can make campus life easier.','创新可以让校园生活更便利。'],
['ability','能力','Reading builds language ability.','阅读培养语言能力。'],
['academic','学术的','The workshop teaches academic writing.','讲座教授学术写作。'],
['compulsory','必修的；强制的','Some courses are compulsory.','有些课程是必修的。'],
['communication','交流','Good communication helps a team.','良好的交流有助于团队合作。'],
['cooperate','合作','Students cooperate on the project.','学生们在项目中合作。'],
['teamwork','团队合作','Teamwork made the event successful.','团队合作使活动成功。'],
['independent','独立的','Independent thinking is useful.','独立思考很有用。'],
['flexible','灵活的','A flexible schedule helps busy students.','灵活的时间安排帮助忙碌的学生。'],
['creative','有创造力的','The club needs creative ideas.','社团需要有创意的想法。'],
['critical','批判性的；重要的','Critical thinking helps us check claims.','批判性思维帮助我们核查说法。'],
['survey','调查','The school sent a survey to students.','学校向学生发出问卷调查。'],
['response','回答；回应','Her response was clear and polite.','她的回应清楚而有礼貌。'],
['submit','提交','Please submit your essay on Friday.','请在周五提交作文。'],
['newspaper','报纸','The university newspaper invited articles.','校报征集文章。'],
['edition','一期；版本','The next edition will discuss campus life.','下一期将讨论校园生活。'],
['facility','设施','The sports facility opens at eight.','体育设施八点开放。'],
['canteen','食堂','The canteen serves lunch at noon.','食堂中午供应午餐。'],
['clinic','诊所','The campus clinic is near the library.','校园诊所在图书馆附近。'],
['delivery','配送','Delivery services save students time.','配送服务节省学生时间。'],
['industry','行业','The service industry employs many people.','服务业雇用许多人。'],
['customer','顾客','The shop asks customers for feedback.','商店向顾客征求反馈。'],
['sustainable','可持续的','A sustainable plan saves resources.','可持续计划节约资源。'],
['recycle','回收利用','We recycle paper and bottles.','我们回收纸张和瓶子。'],
['reusable','可重复使用的','Bring a reusable cup to class.','带一个可重复使用的杯子上课。'],
['pollution','污染','Buses can reduce air pollution.','公交车可以减少空气污染。'],
['carbon','碳','The campus wants to cut carbon emissions.','校园希望减少碳排放。'],
['electric','电动的','She rides an electric bicycle.','她骑电动自行车。'],
['transport','交通；运输','Public transport is cheaper.','公共交通更便宜。'],
['access','使用机会；进入','All students need access to books.','所有学生都需要获得书籍的机会。'],
['accessible','可进入的；易用的','The new website is accessible by phone.','新网站可以用手机访问。'],
['barrier','障碍','Cost can be a barrier to learning.','费用可能是学习的障碍。'],
['cost','花费；成本','The cost of the course is low.','这门课的费用很低。'],
['expense','费用','Travel is our biggest expense.','旅行是我们最大的开支。'],
['budget','预算','I have a small monthly budget.','我的月预算不多。'],
['afford','负担得起','Many students cannot afford a new computer.','许多学生买不起新电脑。'],
['affordable','负担得起的','The meal is healthy and affordable.','这顿饭健康且价格可承受。'],
['economy','经济','Tourism supports the local economy.','旅游业支持当地经济。'],
['economic','经济的','The city faces economic changes.','这座城市面临经济变化。'],
['employment','就业','The course may improve employment chances.','这门课可能增加就业机会。'],
['employee','雇员','An employee answered the call.','一名员工接听了电话。'],
['workplace','工作场所','Teamwork matters in the workplace.','团队合作在职场中很重要。'],
['career','职业生涯','She wants a career in education.','她想从事教育工作。'],
['adapt','适应','Students adapt to new classes.','学生适应新课程。'],
['training','培训','The library provides safety training.','图书馆提供安全培训。'],
['experiment','实验','The class did a simple experiment.','这个班做了一个简单实验。'],
['scientific','科学的','The report uses scientific evidence.','这份报告使用科学证据。'],
['scientist','科学家','The scientist studied water quality.','科学家研究水质。'],
['design','设计','Students design a useful app.','学生设计一个实用应用。'],
['invent','发明','People invent tools to solve problems.','人们发明工具解决问题。'],
['data','数据','The survey data show a clear trend.','调查数据显示明显趋势。'],
['privacy','隐私','Students should protect their privacy.','学生应该保护自己的隐私。'],
['security','安全','A strong password improves security.','强密码提高安全性。'],
['password','密码','Do not share your password.','不要分享你的密码。'],
['account','账户','She checked her online account.','她查看了自己的在线账户。'],
['purchase','购买','Keep a record of each purchase.','保留每笔购买记录。'],
['payment','付款','The app confirms the payment.','应用确认付款。'],
['schedule','日程；安排','Make a study schedule for the week.','制定本周学习计划。'],
['deadline','截止日期','Friday is the deadline for essays.','周五是作文截止日期。'],
['equipment','设备','The lab has new equipment.','实验室有新设备。'],
['repair','修理','Workers will repair the computers.','工作人员将修理电脑。'],
['maintain','维护；保持','The school maintains the sports field.','学校维护运动场。'],
['reliable','可靠的','We need reliable information.','我们需要可靠的信息。'],
['quality','质量','The library checks the quality of its service.','图书馆检查服务质量。'],
['measure','测量；衡量','We measure progress every week.','我们每周衡量进展。'],
['evaluate','评价','The teacher will evaluate our projects.','老师将评价我们的项目。'],
['statistics','统计数据','The statistics show fewer accidents.','统计数据显示事故减少。'],
['percentage','百分比','The percentage rose last year.','这个百分比去年上升了。'],
['trend','趋势','The chart shows a new trend.','图表显示一个新趋势。'],
['contrast','对比','The report contrasts two methods.','报告对比两种方法。'],
['drawback','缺点','One drawback is the high price.','一个缺点是价格高。'],
['concern','担忧；关切','Privacy is a major concern.','隐私是一个主要顾虑。'],
['risk','风险','There is a risk of data loss.','存在数据丢失的风险。'],
['safety','安全','Safety comes first in the lab.','实验室里安全第一。'],
['impact','影响','The new rule has an impact on students.','新规定对学生有影响。'],
['influence','影响','Friends can influence our choices.','朋友可能影响我们的选择。'],
['heritage','文化遗产','The city protects its cultural heritage.','这座城市保护其文化遗产。'],
['ceremony','仪式','The ceremony began at nine.','仪式九点开始。'],
['custom','习俗','This custom is common in the region.','这种习俗在该地区很常见。'],
['respect','尊重','Students show respect for teachers.','学生尊重老师。'],
['rural','乡村的','The program helps rural schools.','该计划帮助乡村学校。'],
['urban','城市的','Urban buses are often crowded.','城市公交常常拥挤。'],
['region','地区','The region is known for tea.','这个地区以茶闻名。'],
['agriculture','农业','Agriculture uses water and land.','农业使用水和土地。'],
['consumer','消费者','Consumers want clear information.','消费者想要清晰的信息。'],
['contribute','贡献','Everyone can contribute an idea.','每个人都能贡献一个想法。'],
['global','全球的','Climate change is a global issue.','气候变化是全球问题。'],
['international','国际的','The club welcomes international students.','社团欢迎国际学生。'],
['foreign','外国的','She is learning a foreign language.','她正在学习一门外语。'],
['expression','表达方式','This is a useful English expression.','这是一个有用的英语表达。'],
['argument','论点','Give one reason for your argument.','为你的论点给出一个理由。'],
['outline','提纲','Write a short outline before the essay.','写作文前列一个简短提纲。'],
['paragraph','段落','Put each main idea in one paragraph.','每个主要观点写成一段。'],
['introduction','引言；开头','The introduction states the topic.','开头说明主题。'],
['conclusion','结论；结尾','The conclusion repeats the main idea.','结尾重申主要观点。'],
['summarize','总结','Summarize the article in one sentence.','用一句话概括文章。'],
['accurate','准确的','Check that the number is accurate.','核对这个数字是否准确。'],
['grammar','语法','Simple grammar can express a clear idea.','简单语法也能表达清楚的想法。'],
['spelling','拼写','Check the spelling before you submit.','提交前检查拼写。'],
['punctuation','标点','Punctuation makes sentences easier to read.','标点让句子更易读。'],
['revise','修改','Revise your essay after feedback.','得到反馈后修改作文。'],
['draft','草稿','Write a first draft without fear.','大胆写第一稿。'],
['feedback','反馈','The teacher gave helpful feedback.','老师给了有帮助的反馈。'],
['criteria','标准','Read the scoring criteria first.','先读评分标准。'],
['coherent','连贯的','A coherent essay is easy to follow.','连贯的作文容易理解。'],
['transition','过渡','Use a transition between ideas.','在观点之间使用过渡语。'],
['moreover','此外','Moreover, the plan costs little.','此外，这个计划花费很少。'],
['nevertheless','尽管如此','Nevertheless, we should try.','尽管如此，我们仍应尝试。'],
['overall','总的来说','Overall, the project was useful.','总的来说，这个项目很有用。']
]);

CLOZE.push(...[
{s:'The new ___ asks students to join a research project.',o:['proposal','festival','weather','breakfast'],a:0,tip:'proposal = 提议；这里指一项让学生参加研究项目的提议。'},
{s:'We should think about both the value and the ___ of the plan.',o:['practicality','spelling','history','colour'],a:0,tip:'practicality = 可行性。'},
{s:'Robots can complete ___ tasks, such as moving books.',o:['repetitive','rural','foreign','private'],a:0,tip:'repetitive = 重复的。'},
{s:'The online system is ___ for students with busy schedules.',o:['convenient','dangerous','traditional','silent'],a:0,tip:'convenient = 方便的。'},
{s:'Please ___ your essay before the deadline.',o:['submit','recycle','invent','repair'],a:0,tip:'submit = 提交。'},
{s:'The teacher asked us to make a short ___ before writing.',o:['outline','payment','device','custom'],a:0,tip:'outline = 提纲。'},
{s:'The report uses survey ___ to support its argument.',o:['data','ceremony','clinic','lunch'],a:0,tip:'data = 数据。'},
{s:'A strong password helps protect online ___.',o:['privacy','agriculture','festival','transport'],a:0,tip:'privacy = 隐私。'},
{s:'Students should ___ the source before sharing a claim.',o:['check','replace','spend','carry'],a:0,tip:'check = 核查。'},
{s:'The school will ___ the broken computers next week.',o:['repair','submit','compare','respect'],a:0,tip:'repair = 修理。'},
{s:'The new bus line gives students easier ___ to the campus.',o:['access','spelling','ceremony','payment'],a:0,tip:'access = 进入或使用的机会。'},
{s:'This meal is healthy and ___ for most students.',o:['affordable','automatic','scientific','global'],a:0,tip:'affordable = 价格可以承受的。'},
{s:'The chart shows a clear ___ in online learning.',o:['trend','clinic','habit','translation'],a:0,tip:'trend = 趋势。'},
{s:'The writer gives one ___ of the idea: it may cost too much.',o:['drawback','benefit','method','goal'],a:0,tip:'drawback = 缺点。'},
{s:'The project will help students develop ___ thinking.',o:['critical','electric','local','reusable'],a:0,tip:'critical thinking = 批判性思维。'},
{s:'Students should ___ for their teachers.',o:['show respect','make budget','take risk','use carbon'],a:0,tip:'show respect for = 尊重。'},
{s:'The city wants to protect its cultural ___.',o:['heritage','password','equipment','deadline'],a:0,tip:'cultural heritage = 文化遗产。'},
{s:'A good ___ states the main idea again.',o:['conclusion','purchase','facility','survey'],a:0,tip:'conclusion = 结论或文章结尾。'},
{s:'The first ___ of the essay introduces the topic.',o:['paragraph','consumer','robot','industry'],a:0,tip:'paragraph = 段落。'},
{s:'The class will ___ two different methods.',o:['evaluate','deliver','borrow','close'],a:0,tip:'evaluate = 评价。'},
{s:'The result is useful; ___, more research is needed.',o:['however','because','first','so'],a:0,tip:'however 表示转折：不过，还需要更多研究。'},
{s:'Students can work together and ___ their ideas.',o:['share','waste','forget','refuse'],a:0,tip:'share ideas = 分享想法。'},
{s:'A ___ source gives information we can trust.',o:['reliable','rural','expensive','repetitive'],a:0,tip:'reliable = 可靠的。'},
{s:'The school asked students to complete a short ___.',o:['survey','ceremony','meal','experiment'],a:0,tip:'survey = 调查问卷。'},
{s:'The teacher gave ___ on my first draft.',o:['feedback','payment','transport','pollution'],a:0,tip:'feedback = 反馈。'},
{s:'The new service may ___ waiting time.',o:['reduce','recycle','invent','submit'],a:0,tip:'reduce waiting time = 减少等待时间。'},
{s:'The team needs a ___ schedule for students with different classes.',o:['flexible','foreign','automatic','global'],a:0,tip:'flexible = 灵活的。'},
{s:'Please check the ___ of names and dates in your report.',o:['accuracy','expense','tradition','career'],a:0,tip:'accuracy = 准确性。'},
{s:'The school provides free ___ on how to use the lab.',o:['training','pollution','ceremony','purchase'],a:0,tip:'training = 培训。'},
{s:'Small acts can ___ to a greener campus.',o:['contribute','replace','purchase','submit'],a:0,tip:'contribute to = 有助于。'}
]);

READINGS.push(...[
{title:'校园科研项目',text:'A university invites first-year students to join small research projects. Each project has a teacher and a team of four students. Students do not need to know every method at the start. They learn by asking questions, collecting information and discussing their results. The school says participation is optional this year.',cn:'一所大学邀请大一学生参与小型研究项目。每个项目有一名老师和四名学生。学生不必一开始就掌握所有方法；他们通过提问、收集资料和讨论结果来学习。今年参加项目是自愿的。',gloss:'research project 科研项目 · method 方法 · result 结果 · optional 自愿的',qs:[{q:'How many students are in each team?',o:['Four','Two','Five','Ten'],a:0,tip:'定位第二句：a team of four students。'},{q:'Must students join this year?',o:['No, it is optional','Yes, everyone must join','Only teachers can join','Only seniors must join'],a:0,tip:'末句 optional = 自愿的。'}]},
{title:'校园机器人',text:'A small robot now carries books between two university libraries. It follows a fixed route and stops when someone is in front of it. The robot saves workers time, but staff still check the books and help readers. The library plans to ask students for feedback before buying another robot.',cn:'一台小机器人现在在大学两个图书馆之间运书。它沿固定路线行走，前方有人时会停下。机器人节省工作人员时间，但员工仍负责检查书籍和帮助读者。图书馆会先征求学生反馈，再决定是否添购。',gloss:'fixed 固定的 · route 路线 · staff 员工 · feedback 反馈',qs:[{q:'What does the robot do?',o:['Carries books','Teaches classes','Writes essays','Cooks meals'],a:0,tip:'首句：carries books。'},{q:'What will the library do before buying another robot?',o:['Ask students for feedback','Close a library','Stop checking books','Change all workers'],a:0,tip:'末句：ask students for feedback。'}]},
{title:'更便利的校园生活',text:'Students at West College often wait in a long line to use the washing machines. A student group suggests a simple booking page. The page would show when each machine is free. The group also asks the school to repair two old machines. These changes may save time without building a new laundry room.',cn:'西院学生使用洗衣机常常排长队。学生小组建议建立简单预约页面，显示每台机器何时空闲，同时请学校维修两台旧机器。这些改变可能无需新建洗衣房就能节省时间。',gloss:'wait in a line 排队 · booking 预约 · repair 维修 · laundry 洗衣',qs:[{q:'What is one proposed solution?',o:['A booking page','A new restaurant','More classes','A larger library'],a:0,tip:'定位第三句：a simple booking page。'},{q:'Why are the changes useful?',o:['They may save time','They add more homework','They close the laundry room','They make machines slower'],a:0,tip:'末句：save time。'}]},
{title:'一杯咖啡的选择',text:'Some students drink coffee before a morning class. A campus survey found that many choose it because they like the taste, while others want to feel more awake. The health center reminds students that coffee cannot replace enough sleep. It suggests drinking water and keeping a regular bedtime.',cn:'有些学生早课前喝咖啡。校园调查发现，许多人是喜欢味道，另一些人则想更清醒。健康中心提醒学生咖啡不能代替充足睡眠，建议喝水并保持规律作息。',gloss:'survey 调查 · awake 清醒的 · replace 代替 · regular 规律的',qs:[{q:'Why do some students choose coffee?',o:['They like the taste','It is required','It replaces all food','It is free'],a:0,tip:'第二句 while 前面：like the taste。'},{q:'What does the health center suggest?',o:['Enough sleep and water','More coffee at night','Skipping breakfast','Less water'],a:0,tip:'末两句强调睡眠和喝水。'}]},
{title:'校园共享单车',text:'The university added a bicycle sharing station near its north gate. Students can borrow a bike with a campus card and return it at any station. The first thirty minutes are free. The school hopes this service will reduce short car trips and make travel between buildings easier.',cn:'学校在北门附近增设共享单车站。学生可用校园卡借车，并在任意站点还车；前 30 分钟免费。学校希望减少短途汽车出行，让楼宇之间的通行更方便。',gloss:'bicycle sharing 共享单车 · return 归还 · free 免费 · reduce 减少',qs:[{q:'How long is the ride free?',o:['Thirty minutes','Ten minutes','One hour','All day'],a:0,tip:'第三句：The first thirty minutes are free。'},{q:'What is one goal of the service?',o:['Reduce short car trips','Sell more cars','Close the north gate','Stop bicycle use'],a:0,tip:'末句：reduce short car trips。'}]},
{title:'写作互评小组',text:'Every Wednesday, six students meet to read one another’s short essays. They first say what is clear and useful. Then they point out one sentence that is hard to understand. The group does not give an exam score. Its goal is to help each writer revise a draft before submitting it.',cn:'每周三，六名学生聚在一起互读短文。他们先说清楚、有用的地方，再指出一个难懂的句子。小组不打考试分数，而是帮助作者在提交前修改草稿。',gloss:'one another 互相 · point out 指出 · revise 修改 · draft 草稿',qs:[{q:'What do students do first?',o:['Say what is clear','Give an exam score','Submit the essay','Leave the room'],a:0,tip:'第二句：first say what is clear。'},{q:'What is the group’s goal?',o:['Help writers revise drafts','Choose a winner','Replace teachers','Write longer tests'],a:0,tip:'末句：help each writer revise a draft。'}]}
]);

LISTENINGS.push(...[
{script:'The research meeting has moved from Room 205 to Room 305. It still begins at three.',q:'会议现在在哪个教室？',o:['305 教室','205 教室','图书馆','实验室'],a:0,tip:'from 205 to 305 表示从 205 改到 305。',cn:'研究会议从 205 教室改到 305 教室，仍是三点开始。'},
{script:'The robot can carry books, but it cannot answer students’ questions. A staff member will help with that.',q:'谁来回答学生的问题？',o:['工作人员','机器人','校长','顾客'],a:0,tip:'but 后面说机器人不能回答，staff member 会帮助。',cn:'机器人能运书，但不能回答学生问题；工作人员会负责。'},
{script:'Please submit the survey by Friday evening. You can complete it on your phone.',q:'问卷什么时候截止？',o:['周五晚上','周四上午','周六晚上','下周一'],a:0,tip:'by Friday evening = 周五晚上之前。',cn:'请在周五晚上前提交问卷，可以用手机完成。'},
{script:'The bus is free for students during the first week. After that, each ride costs one yuan.',q:'第一周学生乘车要多少钱？',o:['免费','一元','两元','十元'],a:0,tip:'during the first week 之后说 free。',cn:'第一周学生免费乘车，此后每次一元。'},
{script:'The writing workshop starts at seven, but the doors open at half past six.',q:'写作讲座几点开始？',o:['七点','六点半','六点','七点半'],a:0,tip:'starts at seven；开门时间 six thirty 是干扰。',cn:'写作讲座七点开始，六点半开门。'},
{script:'Mina planned to print her report at home. Her printer broke, so she used the one in the library.',q:'Mina 最后在哪里打印报告？',o:['图书馆','家里','商店','办公室'],a:0,tip:'so 后是结果：used the one in the library。',cn:'Mina 原计划在家打印，但打印机坏了，于是用了图书馆的打印机。'},
{script:'The campus clinic is closed today. Students can visit the city clinic near the station.',q:'今天学生可去哪看病？',o:['车站附近的市诊所','校园诊所','图书馆','体育馆'],a:0,tip:'campus clinic is closed；city clinic near the station 可去。',cn:'校园诊所今天关闭，学生可到车站附近的市诊所就诊。'},
{script:'The teacher asks each team to give one clear example, not a long list of ideas.',q:'老师要求每组给出什么？',o:['一个清楚的例子','一长串想法','十篇作文','一张照片'],a:0,tip:'one clear example 是关键词。',cn:'老师要求每组给出一个清楚的例子，而非一长串想法。'}
]);

WRITING.push(...[
{type:'写作',prompt:'2026 年 6 月真题主题练习：是否应要求每位大学生至少参加一个科研项目？说明必要性与可行性。',words:'research project 科研项目 · necessity 必要性 · practicality 可行性',frame:'I think this proposal is ___. First, ___. However, ___. Therefore, ___.',model:'I believe research projects can be useful for university students. They give us a chance to ask questions, work with others and learn from real problems. However, requiring every student to join a project may not be practical. Some students have full schedules, and schools need enough teachers to guide each team. I suggest that universities offer small projects and let students choose one that interests them. In this way, more students can benefit from research without feeling that the task is only another rule.',exam:true,keywords:['research','project','student']},
{type:'写作',prompt:'2026 年 6 月真题主题练习：谈谈机器人未来可以怎样服务校园生活，并说明一个需要注意的问题。',words:'robot 机器人 · campus 校园 · service 服务 · privacy 隐私',frame:'Robots may help on campus in several ways. For example, ___. However, ___.',model:'Robots may help make campus life easier. For example, a small robot could carry books between libraries or show visitors the way to a classroom. This would save staff time for work that needs human care. However, a robot should not collect more personal information than necessary. The university should also make sure that it is safe around students. In my view, robots are useful tools, but they should support people rather than replace them.',exam:true,keywords:['robot','campus','student']},
{type:'写作',prompt:'2026 年 6 月真题主题练习：向学校提两项建议，让学生的校园生活更方便。',words:'campus life 校园生活 · convenient 方便的 · suggest 建议',frame:'I would like to suggest two changes. First, ___. Second, ___. These changes would ___.',model:'I would like to suggest two small changes to make campus life easier. First, the school could show available study rooms on one simple website. Students would spend less time looking for a quiet place. Second, it could add clearer signs near the bus stops and main buildings. New students and visitors would then find their way more easily. Neither change needs a large budget, but both could save time every day. I hope the university will consider these ideas.',exam:true,keywords:['campus','student','school']},
{type:'写作',prompt:'模拟主题：大学校园是否应该提供共享单车？说明优点与一个顾虑。',words:'bike sharing 共享单车 · convenient 方便的 · safety 安全',frame:'I support ___. One advantage is ___. However, we should also consider ___.',model:'I support a small bicycle sharing service on campus. It could help students travel between buildings quickly and reduce short car trips. The service should be affordable and easy to use. However, safety is important. The school needs clear parking areas and simple rules for riders. It should also check the bicycles regularly. With these measures, bike sharing can be a convenient and responsible choice for students.',exam:true,keywords:['bike','campus','student']},
{type:'写作',prompt:'模拟主题：怎样利用学校资源培养独立学习能力？',words:'resource 资源 · independent 独立的 · library 图书馆',frame:'Students can use campus resources to ___. First, ___. Also, ___.',model:'Campus resources can help students become independent learners. The library offers books and quiet space, but students need to set their own goals. A writing center can give feedback on an essay, while an online course can help review a difficult lesson. We should choose the resource that fits our problem and then check what we have learned. By taking these small steps regularly, we can make better use of our university and learn with more confidence.',exam:true,keywords:['resource','learn','student']},
{type:'写作',prompt:'模拟主题：学生怎样合理使用 AI 工具，同时保持独立思考？',words:'AI tool AI工具 · think 思考 · check 核查 · learn 学习',frame:'AI tools can help us ___. However, ___. For example, ___.',model:'AI tools can help students learn when used with care. They can explain a new word, offer an example or help us plan a short essay. However, we should try to solve a problem before asking a tool for the full answer. We also need to check the information it gives. If we simply copy its words, we may finish an assignment without understanding it. In my view, AI should support our thinking and practice, not replace them.',exam:true,keywords:['ai','tool','think']}
]);

