let mockTab='overview';
function mockState(){state.mock??={answers:{},writing:'',translation:'',startedAt:null,submittedAt:null,result:null};return state.mock}
function mockQuestion(id,q,o,a,tip){const m=mockState(),done=!!m.submittedAt,chosen=m.answers[id];return `<div class="mock-question"><span class="mock-number">${id.slice(1)}.</span><strong>${escapeHtml(q)}</strong><div class="options">${o.map((v,i)=>`<label class="mock-option ${done&&i===a?'correct':done&&String(i)===chosen&&i!==a?'incorrect':''}"><input type="radio" name="mock-${id}" value="${i}" data-mock-answer="${id}" ${String(i)===chosen?'checked':''} ${done?'disabled':''}><span>${'ABCD'[i]}. ${escapeHtml(v)}</span></label>`).join('')}</div>${done?`<div class="mock-explain">正确答案：${'ABCD'[a]}。${escapeHtml(tip)}</div>`:''}</div>`}
function mockSelect(id,q,letters,answer,tip){const m=mockState(),done=!!m.submittedAt,chosen=m.answers[id]||'';return `<div class="mock-select-row"><label for="mock-${id}"><b>${id.slice(1)}.</b> ${escapeHtml(q)}</label><select id="mock-${id}" data-mock-answer="${id}" ${done?'disabled':''}><option value="">请选择</option>${letters.map(v=>`<option value="${v}" ${v===chosen?'selected':''}>${v}</option>`).join('')}</select>${done?`<small class="mock-explain">答案 ${answer}：${escapeHtml(tip)}</small>`:''}</div>`}
function mockOverview(){return `<div class="mock-intro"><span class="eyebrow">ORIGINAL PRACTICE PAPER · 2026</span><h2>${MOCK.title}</h2><p>按现行四级结构编写：写作 1 篇、听力 25 题、选词填空 10 题、长篇匹配 10 题、仔细阅读 10 题、翻译 1 段。建议总练习时间 125 分钟，可以分段完成，答案自动保存在本机浏览器。</p><div class="mock-info"><span>写作 30 分钟</span><span>听力 25 分钟</span><span>阅读 40 分钟</span><span>翻译 30 分钟</span></div><p class="muted">本卷内容为原创模拟，不是真题或官方预测；听力使用浏览器英语语音合成。</p><button class="primary" id="mockStart">开始模拟卷 →</button></div>`}
function mockWriting(){const m=mockState();return `<article class="question-card mock-section"><span class="tag">Part I · Writing · 30 minutes</span><h2>写作</h2><p>${escapeHtml(MOCK.writing.prompt)}</p><p class="gloss">中文提示：${escapeHtml(MOCK.writing.cn)}</p><textarea class="mock-textarea" data-mock-text="writing" ${m.submittedAt?'disabled':''} placeholder="在这里写 120–180 词。先写观点，再写两点理由或例子。">${escapeHtml(m.writing)}</textarea><small id="mockWordCount">${(m.writing.match(/[A-Za-z]+(?:'[A-Za-z]+)?/g)||[]).length} 词</small>${m.submittedAt?gradeReportHtml(gradeEssay(m.writing,{keywords:MOCK.writing.keywords,exam:true}))+`<details><summary>查看参考写法</summary><p class="english">${escapeHtml(MOCK.writing.model)}</p></details>`:''}</article>`}
function mockListening(){let n=0;const m=mockState();return `<article class="question-card mock-section"><span class="tag">Part II · Listening · 25 questions</span><h2>听力理解</h2><p class="muted">每篇先播放，再答对应题目。播放可重复；交卷后显示原文。语音是系统合成的原创录音。</p>${MOCK.listening.map((g,j)=>`<section class="mock-passage"><h3>${escapeHtml(g.type)}</h3><button class="soft" data-mock-play="${j}">🔊 播放这篇英语</button>${m.submittedAt?`<details><summary>查看听力原文</summary><p class="english">${escapeHtml(g.script)}</p></details>`:''}${g.qs.map(q=>{n++;return mockQuestion('L'+n,q.q,q.o,q.a,q.tip)}).join('')}</section>`).join('')}</article>`}
function mockCloze(){const c=MOCK.cloze,m=mockState();const text=c.text.replace(/\[(\d+)\]/g,(_,num)=>`<span class="mock-blank">${num} ______</span>`);return `<section class="mock-passage"><h3>Section A · 选词填空（26–35）</h3><p class="english">${text}</p><div class="word-bank">${Object.entries(c.options).map(([letter,word])=>`<span><b>${letter}</b> ${escapeHtml(word)}</span>`).join('')}</div><div class="mock-select-list">${Object.keys(c.answers).map(num=>mockSelect('C'+num,'选择适合第 '+num+' 空的词',Object.keys(c.options),c.answers[num],c.tips[num])).join('')}</div></section>`}
function mockMatching(){const x=MOCK.matching;return `<section class="mock-passage"><h3>Section B · 长篇阅读匹配（36–45）</h3><h4>${escapeHtml(x.title)}</h4><p class="muted">先看句子，再回到各段找同义信息。每段可能被选择一次或多次。</p><div class="matching-text">${Object.entries(x.paragraphs).map(([letter,text])=>`<p><b>${letter}.</b> ${escapeHtml(text)}</p>`).join('')}</div><div class="mock-select-list">${x.qs.map((q,i)=>mockSelect('M'+(i+36),q.q,Object.keys(x.paragraphs),q.a,q.tip)).join('')}</div></section>`}
function mockCareful(){let n=45;return MOCK.careful.map(x=>`<section class="mock-passage"><h3>Section C · 仔细阅读</h3><h4>${escapeHtml(x.title)}</h4><p class="english">${escapeHtml(x.text)}</p>${x.qs.map(q=>{n++;return mockQuestion('R'+n,q.q,q.o,q.a,q.tip)}).join('')}</section>`).join('')}
function mockReading(){return `<article class="question-card mock-section"><span class="tag">Part III · Reading · 30 questions</span><h2>阅读理解</h2>${mockCloze()}${mockMatching()}${mockCareful()}</article>`}
function mockTranslation(){const m=mockState();return `<article class="question-card mock-section"><span class="tag">Part IV · Translation · 30 minutes</span><h2>汉译英</h2><p>${escapeHtml(MOCK.translation.prompt)}</p><textarea class="mock-textarea" data-mock-text="translation" ${m.submittedAt?'disabled':''} placeholder="先写简单、准确的英文句子，再补充细节。">${escapeHtml(m.translation)}</textarea>${m.submittedAt?`<details open><summary>查看参考译文（无自动评分）</summary><p class="english">${escapeHtml(MOCK.translation.model)}</p></details>`:''}</article>`}
function mockResults(){const m=mockState(),r=m.result;if(!r)return '';return `<article class="question-card mock-section"><span class="eyebrow">练习结果 · 不能换算四级报道分</span><h2>客观题答对 ${r.correct} / 55</h2><div class="metrics mock-metrics"><div><strong>${r.listening} / 25</strong><span>听力</span></div><div><strong>${r.cloze} / 10</strong><span>选词填空</span></div><div><strong>${r.matching} / 10</strong><span>长篇匹配</span></div><div><strong>${r.careful} / 10</strong><span>仔细阅读</span></div></div><p>还有 ${r.unanswered} 道客观题未作答。进入各部分可以看答案、听力原文和逐题解析。</p>${m.writing.trim()?gradeReportHtml(gradeEssay(m.writing,{keywords:MOCK.writing.keywords,exam:true})):'<p>写作未作答，因此没有写作练习估分。</p>'}<p class="notice">翻译没有自动评分，请进入「翻译」对照参考译文。写作估分只检查部分常见错误，不能当作考试成绩。</p><button class="soft" id="mockReset">保存本次结果并重新练习</button></article>`}
function mock(){const m=mockState();if(!m.startedAt)return `<section class="page-head"><span class="eyebrow">PRACTICE EXAM</span><h1>2026 冲刺模拟卷</h1><p>一套完整题型的原创练习卷，适合学过基础词和短文后使用。</p></section>${mockOverview()}`;const count=Object.keys(m.answers).length;const tabs=[['writing','写作'],['listening','听力'],['reading','阅读'],['translation','翻译'],['results','结果']];return `<section class="page-head"><span class="eyebrow">ORIGINAL MOCK · 2026 AUTUMN</span><h1>${MOCK.title}</h1><p>已答 ${count} / 55 道客观题 · 用时 <span id="mockClock">${Math.floor((Date.now()-m.startedAt)/60000)} 分钟</span> · ${m.submittedAt?'已交卷，可看解析':'进度自动保存'}</p></section><div class="switcher mock-tabs">${tabs.filter(t=>t[0]!=='results'||m.submittedAt).map(([id,label])=>`<button class="chip ${mockTab===id?'selected':''}" data-mock-tab="${id}">${label}</button>`).join('')}</div>${({writing:mockWriting,listening:mockListening,reading:mockReading,translation:mockTranslation,results:mockResults}[mockTab]||mockWriting)()}${!m.submittedAt?`<div class="mock-submit"><span>可以分段完成，交卷后显示答案与写作练习估分。</span><button class="primary" id="mockSubmit">交卷并查看结果</button></div>`:''}`}
function scoreMock(){const m=mockState();let listening=0,cloze=0,matching=0,careful=0;let n=0;for(const g of MOCK.listening)for(const q of g.qs){n++;if(m.answers['L'+n]===String(q.a))listening++}for(const [num,letter] of Object.entries(MOCK.cloze.answers))if(m.answers['C'+num]===letter)cloze++;MOCK.matching.qs.forEach((q,i)=>{if(m.answers['M'+(i+36)]===q.a)matching++});n=45;for(const p of MOCK.careful)for(const q of p.qs){n++;if(m.answers['R'+n]===String(q.a))careful++}return {listening,cloze,matching,careful,correct:listening+cloze+matching+careful,unanswered:55-Object.keys(m.answers).filter(k=>/^[LCMR]\d+$/.test(k)).length}}
document.addEventListener('click',e=>{
  const m=mockState();
  if(e.target.id==='mockStart'){m.startedAt=Date.now();m.submittedAt=null;m.answers={};m.writing='';m.translation='';mockTab='writing';save();render()}
  if(e.target.dataset.mockTab){mockTab=e.target.dataset.mockTab;render();window.scrollTo({top:0,behavior:'smooth'})}
  if(e.target.dataset.mockPlay!==undefined)speak(MOCK.listening[Number(e.target.dataset.mockPlay)].script,.82);
  if(e.target.id==='mockSubmit'){m.submittedAt=Date.now();m.result=scoreMock();mockTab='results';save();render();window.scrollTo({top:0,behavior:'smooth'})}
  if(e.target.id==='mockReset'){state.mockHistory??=[];state.mockHistory.push({date:today(),result:m.result,writing:m.writing});state.mock={answers:{},writing:'',translation:'',startedAt:null,submittedAt:null,result:null};mockTab='overview';save();render()}
});
document.addEventListener('change',e=>{if(!e.target.dataset.mockAnswer)return;const m=mockState();if(m.submittedAt)return;m.answers[e.target.dataset.mockAnswer]=e.target.value;save()});
document.addEventListener('input',e=>{const field=e.target.dataset.mockText;if(!field)return;const m=mockState();if(m.submittedAt)return;m[field]=e.target.value;save();if(field==='writing'){const c=document.querySelector('#mockWordCount');if(c)c.textContent=(e.target.value.match(/[A-Za-z]+(?:'[A-Za-z]+)?/g)||[]).length+' 词'}});
setInterval(()=>{const el=document.querySelector('#mockClock');if(el&&typeof state!=='undefined'&&state.mock?.startedAt)el.textContent=Math.floor((Date.now()-state.mock.startedAt)/60000)+' 分钟'},15000);
