const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const source=path.join(root,'source-app');
const target=path.join(root,'www');
const overlay=path.join(root,'web-src');
const copy=(from,to)=>{fs.mkdirSync(path.dirname(to),{recursive:true});fs.cpSync(from,to,{recursive:true,force:true})};
if(!fs.existsSync(path.join(source,'index.html')))throw Error('Study app not found: '+source);
fs.rmSync(target,{recursive:true,force:true});
copy(source,target);
for(const item of fs.readdirSync(overlay))copy(path.join(overlay,item),path.join(target,item));
fs.mkdirSync(path.join(target,'vendor'),{recursive:true});
for(const file of ['pdf.mjs','pdf.worker.mjs'])copy(path.join(root,'node_modules','pdfjs-dist','build',file),path.join(target,'vendor',file));
for(const folder of ['cmaps','standard_fonts'])copy(path.join(root,'node_modules','pdfjs-dist',folder),path.join(target,'vendor',folder));
const index=path.join(target,'index.html');
let html=fs.readFileSync(index,'utf8');
html=html.replace('<meta name="color-scheme" content="light">','<meta name="color-scheme" content="light">\n  <meta name="theme-color" content="#153e32">\n  <meta name="apple-mobile-web-app-capable" content="yes">\n  <meta name="apple-mobile-web-app-status-bar-style" content="default">\n  <link rel="manifest" href="manifest.webmanifest">\n  <link rel="icon" type="image/png" sizes="192x192" href="icon-192.png">\n  <link rel="apple-touch-icon" href="icon-192.png">');
html=html.replace('</body>','  <script src="mobile-assets.js" defer></script>\n  <script src="register-sw.js" defer></script>\n</body>');
fs.writeFileSync(index,html);
console.log('Prepared mobile web assets:',target);
